"""The public introduction to the book: a visual essay with source-exact extracts."""
from html import escape as e
STORIES=[
 (1,'Beneath an ordinary field','Before the throne appears, there is grass, cattle and a familiar patch of earth. Authority enters this everyday world almost unnoticed. The opening asks us to look again at the ground on which a ruler stands.'),
 (8,'An old epic, an unfinished question','The poem turns to the world of the Mahabharata, looking beyond territory to the choices made in the presence of power. The past becomes a way of asking what a person will accept, resist or help to preserve.'),
 (15,'A new name. The same seat.','A change of name or outward appearance does not settle the question of rule. The poem looks for continuity beneath transformation: what survives when the figure on the throne seems to have changed?'),
 (65,'When conviction becomes performance','Persuasion, commerce and public spectacle meet in a crowded marketplace. Moral language becomes something that can be displayed and sold. The poem’s satire turns from the stage towards the audience watching it.'),
 (68,'The beginning returns','Gates open and the ordinary world begins to breathe again. Yet the mound waits. The closing poem brings us back towards the first, holding hope beside the possibility that the old pattern may return.')
]
def render_home(chapters,art,icon,excerpt,cover_face):
    scenes=[]
    for order,(number,title,narrative) in enumerate(STORIES,1):
        c=next(c for c in chapters if c['number']==number);a=art[number]
        scenes.append(f'''<section class="story-scene {'story-reverse' if order%2==0 else ''}" aria-labelledby="story-{number}"><figure><img src="assets/poems/unique/poem-{number:02}.png" width="1536" height="1024" alt="{e(a['alt'])}" loading="lazy"></figure><div class="scene-copy"><p class="story-number" lang="en">{order:02} <span>From poem {number:02}</span></p><h2 id="story-{number}" lang="en">{e(title)}</h2><p class="scene-narrative" lang="en">{e(narrative)}</p><blockquote lang="or">{excerpt(c,3)}</blockquote><a class="story-read" href="poem-{number}.html" lang="en">Enter this poem {icon('read')}</a></div></section>''')
    return f'''<section class="home-opening"><div class="home-introduction" lang="en"><p class="eyebrow">Pravakar Satapathy’s first book</p><h1>A poet looks<br>at power.</h1><p class="home-deck">An Odia journey through the throne, the people around it, and the lives that continue beneath its shadow.</p><p>Written during a period when the poet was active in politics, these sixty-eight poems bring myth, history and public life into conversation. Their connections reach from the court to the village, from the language of authority to the questions of an ordinary person.</p><div class="home-reading-links"><a class="home-primary" href="book.html">{icon('read')}Read the illustrated book</a><a href="intro.html?focus=1">Read quietly <span aria-hidden="true">↗</span></a><a href="listen.html">Listen to the poems <span aria-hidden="true">↗</span></a></div><a class="home-explore" href="#visual-story">Explore the book’s world ↓</a></div><figure class="home-cover bound-cover bound-front"><a href="book.html" aria-label="Open the illustrated book">{cover_face('front')}</a></figure></section>
<section class="home-poet" aria-labelledby="home-poet-title"><figure><img src="assets/writers/41-earth-voice-v1.png" width="1086" height="1448" alt="Portrait of Pravakar Satapathy" loading="lazy"></figure><div lang="en"><p class="eyebrow">The poet &amp; his world</p><h2 id="home-poet-title">Political life.<br>A poet’s searching eye.</h2><p>Pravakar Satapathy wrote his first book while actively involved in politics. He was also a poet drawing connections: between rulers and the ruled, remembered stories and contemporary life, the promise of change and the persistence of power.</p><p>The throne gives those encounters a recurring place to gather. Across the poems, its meaning shifts with the people who seek it, serve it, question it or live in its shadow.</p><p class="home-poet-name" lang="or">ପ୍ରଭାକର ଶତପଥୀ</p><a class="story-read" href="author.html">Meet the poet <span aria-hidden="true">→</span></a></div></section>
<div class="visual-story-heading" id="visual-story" lang="en"><span aria-hidden="true">{icon('talapatra')}</span><p class="eyebrow">A journey in images &amp; verse</p><h2>Five glimpses into the book</h2><p>Read the original Odia words alongside a visual and English narrative of the world they open.</p></div>
<div class="home-visual-story">{''.join(scenes)}</div>
<section class="home-reading-choice" aria-labelledby="choose-reading" lang="en"><p class="eyebrow">Enter the book</p><h2 id="choose-reading">Two ways to turn its pages.</h2><div class="reading-choices"><a href="book.html"><span class="choice-icon" aria-hidden="true">{icon('read')}</span><h3>The illustrated book</h3><p>Paintings, image stories and the complete Odia poems, unfolding together as you turn the pages.</p><span class="choice-link">Open the illustrated book →</span></a><a href="intro.html?focus=1"><span class="quiet-aa" aria-hidden="true">Aa</span><h3>Quiet reading</h3><p>Only the words. An uncluttered, image-free book with text sizing, bookmarks and underlining.</p><span class="choice-link">Read quietly →</span></a></div><a class="home-contents-link" href="contents.html">Browse all poems</a></section>'''
